name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create Database
      run: |
        touch tests/vendor/temp/database.sqlite
        chmod 775 tests/vendor/temp/database.sqlite

    - name: Run tests
      run: vendor/bin/phpunit --coverage-clover tests/vendor/temp/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: tests/vendor/temp/coverage.xml
